### PR TITLE
Added --passWithNoTests to adap-b04 to adap-b06

### PR DESCRIPTION
**Pull request by JudithWell**
I added --passWithNoTests to test commands for the new Homework projects that didn't have any test files yet.

### CODE REVIEW

**Comment by JudithWell** [comment]
I can't accept the License as "Moritz Gorny", because I configured my local git bash really terribly: with a typo in my email. So the email that supposedly performed that commit likely does not even exist. I hope we can still add this commit?
Moritz

**Comment by joluj** [comment]
Can you redo this PR? Either force push or close this and open a new one with the proper authors.

Thanks

**Comment by JudithWell** [comment]
I redid the PR here: [https://github.com/riehlegroup/adap-names/pull/12](https://github.com/riehlegroup/adap-names/pull/12)

**Comment by JudithWell** [comment]
I am closing this request.

**Pull request closed without merging**
